### ISSUE TITLE
[bug] Dependency on `release-it`

### ISSUE THREAD

**Issue by mirus-ua** [soorria/solid-dropzone#1]
I started plating with freshly created __Solid Start__ project that was scaffolded via `yarn create solid` and found that the package `solid-dropzone` cause an error that the devserver can't get `release-it`. The traceback below 
```
  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  Inspect: http:/localhost:3000/__inspect/
  ➜  press h to show help
✘ [ERROR] Could not resolve "release-it"

    node_modules/@release-it/keep-a-changelog/index.js:1:27:
      1 │ const { Plugin } = require('release-it');
        ╵                            ~~~~~~~~~~~~

  You can mark the path "release-it" as external to exclude it from the bundle, which will remove
  this error. You can also surround this "require" call with a try/catch block to handle this
  failure at run-time instead of bundle-time.

An unhandled error occured: Error: Build failed with 1 error:
node_modules/@release-it/keep-a-changelog/index.js:1:27: ERROR: Could not resolve "release-it"
    at failureErrorWithLog (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:1604:15)
    at /Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:1056:28
    at runOnEndCallbacks (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:1476:61)
    at buildResponseToResult (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:1054:7)
    at /Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:1166:14
    at responseCallbacks.<computed> (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:701:9)
    at handleIncomingPacket (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:756:9)
    at Socket.readFromStdout (/Users/mirus/code/eigurt/node_modules/vite/node_modules/esbuild/lib/main.js:677:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
```

When I added `release-it` as a dev dependency the error was gone.

**Comment by soorria** [comment]
I think this is unrelated to this package, since `release-it` isn't anywhere in the `pnpm-lock.yaml` file, but I'll take a closer look later today.

**Comment by mirus-ua** [comment]
Yes, I also looked through the `package` file

Here are the steps for reproduce: 
- yarn create solid
- ✔ Which template do you want to use? › bare
- ✔ Server Side Rendering? … yes
- ✔ Use TypeScript? … yes
-  yarn install
- yarn dev (at this moment everything works)
- stop terminal
- yarn add solid-dropzone
- yarn dev (here the error)

macos 13.1 (22C65) with M1

**Comment by soorria** [comment]
haha realised what the issue is - you're using [`solid-dropzone`](https://github.com/patrick-salvatore/solid-dropzone), not `@soorria/solid-dropzone`.

**Comment by mirus-ua** [comment]
Haha. I used the line from the readme and didn't recheck. Let's change the readme and maybe add a small example to it
